/* SCRIPT 01: CARGA BRUTA (STAGING)
   Objetivo: Criar a estrutura inicial para receber o CSV do INEP.
   Estratégia: Uso de tipos TEXT para evitar erros de importação.
*/

DROP TABLE IF EXISTS fluxo_discente_bruto;

CREATE TABLE fluxo_discente_bruto (
    no_regiao TEXT,
    qt_curso TEXT,
    qt_vg_total TEXT,
    qt_vg_total_diurno TEXT,
    qt_vg_total_noturno TEXT,
    qt_vg_total_ead TEXT,
    qt_ing TEXT,
    qt_ing_fem TEXT,
    qt_ing_masc TEXT,
    qt_ing_diurno TEXT,
    qt_ing_noturno TEXT,
    qt_ing_branca TEXT,
    qt_ing_preta TEXT,
    qt_ing_parda TEXT,
    qt_ing_amarela TEXT,
    qt_ing_indigena TEXT,
    qt_mat TEXT,
    qt_mat_fem TEXT,
    qt_mat_masc TEXT,
    qt_mat_diurno TEXT,
    qt_mat_noturno TEXT,
    qt_mat_branca TEXT,
    qt_mat_preta TEXT,
    qt_mat_parda TEXT,
    qt_mat_amarela TEXT,
    qt_mat_indigena TEXT,
    qt_conc TEXT,
    qt_conc_fem TEXT,
    qt_conc_masc TEXT,
    qt_conc_diurno TEXT,
    qt_conc_noturno TEXT,
    qt_conc_branca TEXT,
    qt_conc_preta TEXT,
    qt_conc_parda TEXT,
    qt_conc_amarela TEXT,
    qt_conc_indigena TEXT,
    qt_sit_trancada TEXT,
    qt_sit_desvinculado TEXT,
    qt_sit_transferido TEXT,
    qt_sit_falecido TEXT,
    no_curso TEXT,
    tp_organizacao_academica TEXT,
    tp_rede TEXT,
    tp_categoria_administrative TEXT,
    tp_grau_academico TEXT,
    tp_modalidade_ensino TEXT,
    tp_nivel_academico TEXT,
    qt_inscrito_total TEXT,
    qt_inscrito_total_diurno TEXT,
    qt_inscrito_total_noturno TEXT,
    qt_inscrito_total_ead TEXT,
    sg_uf TEXT,
    nu_ano_censo TEXT,
    co_ies TEXT,
    no_curso_1 TEXT,
    co_curso TEXT,
    in_gratuito TEXT
);
